libretro/vice-libretro

libretro/libretro-core.c
Request and store a reference to the front-end log callback.
Replaced some immediate uses of printf and fprintf(stderr, with this.
=> Log Callback

Makefile.libretro, libretro/libretro-core.c
Add git revision to core version string - based on code used by the Beetle Saturn core.
=> Append git revision to core version string.

Makefile.common, README.MD, libretro/libretro-core.c, libretro/retro_disk_control.c, libretro/retro_disk_control.h, libretro/retro_files.c, libretro/retro_files.h, libretro/retro_strings.c, libretro/retro_strings.h
Support for m3u files and disk control for disk switching.
Documentation was also updated.
Fixes #54
=> Added m3u and disk control support

README.MD, libretro/libretro-core.c, vice/data/C128/colodore.vpl, vice/data/CBM-II/colodore.vpl, vice/data/SCPU64/colodore.vpl, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/archdep.h, vice/src/c128/c128embedded.c, vice/src/cbm2/cbm5x0embedded.c, vice/src/lib/libffmpeg/libavutil/file.c, vice/src/main.c
Closes #53 
Tested and ready to merge.
=> Fix more crashes with colodore palettes, use system dir correctly

libretro/libretro-core.c, libretro/nukleargui/gui.i, vice/src/arch/libretro/uistatusbar.c
=> Proper NTSC+PAL values for system_av_info

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
If it would be of any help for the most unfortunate hardware.
Default is the heaviest.
=> reSID sampling core option

libretro/libretro-core.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h, libretro/nukleargui/vkboard.i
Vkbd control handling now all cases & temporary android eyecandy stripping
=> Feature fix and more testing for android mystery

libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/nuklear/style.c, libretro/nukleargui/vkboard.i
Also removed the unknowns, because why not.
=> Core option for models more human readable

libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/uistatusbar.c
The datasette controls can be toggled on/off and the toggle can also be assigned to a hotkey.
Did I miss something?
Closes #67
=> Datasette controls and m3u support

libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/autostart.c
Commit comments should speak for themselves
=> Minor enhancements

vice/src/arch/libretro/uistatusbar.c
More appealing joyport information.
=> Statusbar pimpin'

libretro/libretro-core.c, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/retrostubs.c
The snapshot feature uses RA save directory and names the files according RPATH.
It isn't too reliable yet, but better than nothing.
Also some core option logistics.
=> Experimental poor man's savestate

Makefile.libretro, libretro/include/config.h, vice/src/arch/libretro/archdep.c
Fixes #93
Feel free to clean up the code as needed.
Thanks!
=> Fix build for PSP

libretro/nukleargui/retro/nuklear_retro_soft.h
Minor thing again, because major things appear to be exhausted
=> Allow Enter to trigger VKBD keys with keyboard device type

Makefile.libretro, libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/retro/retro_surface.c, vice/src/arch/libretro/archdep.h, vice/src/arch/libretro/defaultkey.inc
Disabled VICE debugs from makefile and put retro-related printfs under RETRO_DEBUG and disabled that too.
=> Verbose log tidying

libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/retro/nuklear_retro_soft.h, vice/src/arch/libretro/retrostubs.c
Also confined mouse cursor to the key area on mouse move.
=> Cleaned unused stuff + proper names for turbofire buttons + minor alterations to sublabels

libretro/libretro-core.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
Statusbar indicator for normal fps and warp mode cleaned up.
One less core option with a combined drive sound emulation option.
NumLock as drive LED indicator option only for WIN32 for now, because that I can test, so assistance is much appreciated!
=> Small improvements

libretro/libretro-core.c
Also moved the turbo fire core options to the end for quicker access.
=> Minor esthetics

libretro/libretro-core.c, libretro/libretro-core.h, libretro/nukleargui/app.c, libretro/nukleargui/nuklear/style.c, libretro/nukleargui/retro/nuklear_retro_soft.h, libretro/nukleargui/vkboard.i, libretro/vkbd.i, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/uistatusbar.c
More faithful keyboard layout with also Datasette controls.
=> New VKBD layout

README.MD
Add command file usage to docs
=> Add command file usage to docs

libretro/libretro-core.c, vice/src/initcmdline.c, vice/src/initcmdline.h
=> WIP: Fix for cartridge from vicerc ignored

libretro/nukleargui/nuklear/style.c, libretro/nukleargui/retro/nuklear_retro_soft.h, libretro/vkbd.i, vice/src/arch/libretro/retrostubs.c
Brought a few things already added in the PUAE core:
- Some trainers use C= key (mapped to LCtrl), and if using keyboard to control RetroPad with LCtrl as fire button, the trainer key was pressed
- Selected VKBD key is not movable when key is held down
Bonus:
- VKBD theme tunings
- Some cleanings
=> Usability maintenance

libretro/libretro-core.c, vice/src/arch/libretro/uistatusbar.c
Found a couple missing null terminations + more tidying.
Bonus: Show userport joyports in statusbar dynamically
=> More minor tidyings

libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h, libretro/nukleargui/vkboard.i, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
VIC20:
- Irrelevant core options (SID + RetroPad Port) removed
- Joyport forced to Port 1
- Memory expansions core option added
- Statusbar position fixed
- VKBD position + size fixed
Closes #63 
Bonus:
- Core options renamed to comply with standalone VICE
- Tidyings + indentations
=> VIC20 updates

libretro/include/retroscreen.h, libretro/libretro-core.c, libretro/libretro-core.h, libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/uistatusbar.c, vice/src/arch/libretro/vsyncarch.c
- Zoom option with three reasonable modes (only for x64, x64sc & xvic for now)
- Added all the other RetroPad buttons to the keyboard pass-through function
+ Bonus readability cleanups & logistics
=> Zoom mode core option

libretro/libretro-core.c
Was a bit too hasty there, but now we are cooking.
=> Aspect ratio fixes

libretro/libretro-core.c, vice/src/arch/libretro/vsyncarch.c, vice/src/socket.c, vice/src/tapeport/tapecart.c
Much nicer at least on Windows.
And a hefty bonus of one frame less input lag with a simple change.
=> Fix compilation warnings

libretro/libretro-core.c
Version-information sometimes will not be returned. As this wasn't
handled properly the codepath for the old API-version would be run
unintended.
This codepath caused memory-corruption with more than 63 core-options.
=> Core-options legacy API: Fix overflow and unintended call

Makefile, libretro-common/include/retro_endianness.h, libretro/include/config.h
This adds the support for big-endian linux
=> Switch from adhoc endianness handling to retro_endianness.h

libretro/libretro-core.c, libretro/libretro-core.h
- Presets for usual suspects (16:9, 16:10, 4:3, 5:4)
- Hardcode exceptions minimized, math maximized with science
=> Zoom improvements

libretro/libretro-core.c
Zoom mode:
- Changed manual mode operation from automatic to optional
- Corrected non-wide calculations (still not perfect though)
- Added VIC-II/VIC/TED border info to sublabels
Bonus:
- Fixed behavior when changing model while running region forced content
=>  Zoom mode honing, Automatic region fixes

libretro/libretro-core.c
Oops that this went overlooked for so long. I feel the shared button/hotkey is enough for now.
Closes #247
=> Freeze cartridge to reset types

libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c
- Special hotkeys can override VKBD functions
=> Remapping fixes + clarifications

COPYING
Simply copied it to the place where github picks it up.
=> Add GPL license

Makefile, README.md, libretro/libretro-core.c, libretro/libretro-mapper.c, libretro/libretro-mapper.h, vice/src/arch/libretro/ui.c
- Added hotkey for toggling Pixel Aspect Ratio
- Mapper code readability improvements
- Removed default VKBD keyboard hotkey due to conflict with RA defaults
- Removed odd url from makefile
- Reformatted Readme tables + cleanup
=> Aspect Ratio toggle Hotkey, Maintenance

Makefile, deps/nibtools/lz.c, include/PS3_include.h, include/config.h, libretro/retro_files.c, vice/src/arch/libretro/archdep.c, vice/src/config.h, vice/src/ioutil.c, vice/src/ioutil.h, vice/src/monitor/asm6502.c, vice/src/monitor/montypes.h, vice/src/resid/sid.cc, vice/src/residfp/builders/residfp-builder/residfp/FilterModelConfig.cpp, vice/src/residfp/builders/residfp-builder/residfp/OpAmp.cpp, vice/src/residfp/builders/residfp-builder/residfp/WaveformCalculator.cpp, vice/src/residfp/builders/residfp-builder/residfp/resample/SincResampler.cpp, vice/src/residfp/builders/residfp-builder/residfp/resample/TwoPassSincResampler.h
=> vice_x64 - PS3 build fix

libretro/libretro-dc.c
Tabs and 4 spaces to 3 spaces + potential crash fix.
=> DC cleanup

libretro/libretro-graph.c, libretro/libretro-graph.h, vice/src/arch/libretro/uistatusbar.c
- Tape indicator icons
- More Android attempts
=> Statusbar tunings

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-glue.c, libretro/libretro-mapper.c, libretro/libretro-vkbd.h, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/types.h
VIC-20:
- Fixed issue with zipped cartridges
- Added parsing and running `(SYS x)` from filename
Other:
- Statusbar char width + more information like in PUAE
=> VIC-20 file compatibility improvements, Statusbar enhancements

libretro/libretro-core.c, vice/src/arch/libretro/uistatusbar.c, vice/src/drive/drive.c
Separated one single LED to:
- Power
- Floppy
- Tape
=> LED interface improvements

README.md, libretro/libretro-core.c, libretro/libretro-dc.c
Yet again sorting the hassle of VIC-20 cart memory address.
=> More VIC-20 fixes, Readme updates

Makefile.x128, Makefile.x64, Makefile.x64sc, Makefile.xcbm2, Makefile.xcbm5x0, Makefile.xpet, Makefile.xplus4, Makefile.xscpu64, Makefile.xvic, libretro/libretro-core.c, libretro/libretro-glue.c, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h, vice/src/arch/libretro/archdep.h, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/main.c, vice/src/resid/resid-config.h, vice/src/residfp/builders/residfp-builder/residfp/SID.h, vice/src/residfp/builders/residfp-builder/residfp/siddefs-fp.h, vice/src/sid/resid-fp.cc, vice/src/sid/sid.h, vice/src/sound.h, vice/src/sounddrv/soundretro.c
- Stereo output with extra SID
Closes #310 
- SID corrections (old 8580 filters replaced with new)
- TEMP-dir cleaning
- Added Zoom Mode + Aspect Ratio toggle to VKBD under CapsLock
- Release all RetroPad controls when VKBD is toggled
- Statusbar FPS shows more useful numbers than >99 (100 = C, 1000 = K)
=> VKBD additions, Stereo SID

libretro/libretro-core.c, libretro/libretro-mapper.c, libretro/libretro-vkbd.c
VKBD:
- Size simplifications
- CapsLock keydown while VKBD visible
Other:
- Revert PERF_INTERFACE requirement
- Ensure proper geometry size before first run
Closes #343
=> VKBD fixes, Geometry fix

Makefile, include/config.h, libretro/libretro-core.c, libretro/libretro-glue.c, vice/src/arch/libretro/uistatusbar.c
=> Fix static build restart, Makefile cleanup

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
- Remaining SuperCPU core options added: SIMM Size + Speed Switch
- Autodetect `.reu` image files
- DC cleanup
=> SuperCPU changes

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-vkbd.c, vice/src/arch/libretro/uistatusbar.c
- Better readability with font outline instead of simple shadow
- Reworked core option with new "Automatic" default
- Statusbar color adjustments
=> VKBD improvements

libretro/libretro-core.c, libretro/libretro-vkbd.c
Let's make the new fancy text outline optional due to performance concerns.
=> Optional VKBD text outline

libretro/libretro-core.c, libretro/libretro-graph.c, libretro/libretro-graph.h, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h, vice/src/arch/libretro/uistatusbar.c
Cleanups and a lot faster font outline mode.
=> VKBD+graph optimizations

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-glue.c, libretro/libretro-graph.c, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, vice/src/arch/libretro/mousedrv.c, vice/src/sounddrv/soundretro.c
VKBD:
- Color adjustments
- Waits for all inputs to be released before accepting inputs
Other:
- Mouse emulation adjustments
- Dpad mouse acceleration fixed
- Audio cleanups
=> VKBD + input updates

libretro/libretro-dc.c
Leak hunt broke labels so that all disks had the first disk label, oops..
=> Fix DC file labels

vice/src/autostart.c
=> Fix .d64 loading error due to missing fclose

Makefile.x128, Makefile.x64, Makefile.x64dtv, Makefile.x64sc, Makefile.xcbm2, Makefile.xcbm5x0, Makefile.xpet, Makefile.xplus4, Makefile.xscpu64, Makefile.xvic, libretro/libretro-core.c, libretro/libretro-core.h, retrodep/ui.c, retrodep/video.c, retrodep/video/renderscale2x.c, retrodep/vsyncarch.c, vice/src/log.c, vice/src/resources.c, vice/src/video/video-render-crt.c, vice/src/video/video-render-pal.c, vice/src/video/video-resources.c
Core option for VIC-II/VIC/TED/CRTC video filter with different levels of horizontal blur.
Closes #383
=> Internal video filter core option

vice/src/resources.c
Comment ignoring was half baked, oops.
Closes #390
=> 'vicerc' comment fix

libretro/libretro-core.c, libretro/libretro-mapper.c, retrodep/uistatusbar.c
- Fixed userport joysticks that have been broken for a while, oops
- Adjusted userport joyports for XVIC and PET so that extra ports start at J2 and J1 respectively
- Bonus memory leak cleanups
=> Joyport fixes

libretro-common/audio/audio_mixer.c, libretro-common/file/archive_file_7z.c, libretro-common/file/nbio/nbio_stdio.c, libretro-common/include/defines/ps3_defines.h, libretro-common/include/libretro.h, libretro-common/include/lists/nested_list.h, libretro-common/include/net/net_compat.h, libretro-common/include/net/net_http.h, libretro-common/include/net/net_natt.h, libretro-common/lists/nested_list.c, libretro-common/net/net_compat.c, libretro-common/net/net_http.c, libretro-common/net/net_natt.c, libretro-common/net/net_socket.c, libretro-common/rthreads/rthreads.c, libretro-common/samples/core_options/README.md, libretro-common/samples/core_options/example_categories/libretro_core_options.h, libretro-common/samples/core_options/example_categories/libretro_core_options_intl.h, libretro-common/vfs/vfs_implementation.c, libretro-common/vfs/vfs_implementation_uwp.cpp, libretro/libretro-core.c
=> Core options V2

libretro/libretro-core.c, libretro/libretro-dc.c, vice/src/autostart.c, vice/src/c64/cart/easyflash.c, vice/src/drive/drive-snapshot.c
- Fixed M3U customized PRG launch from D64s getting cut one character in the end
- Fixed VICE snapshot file launch crashes if EasyFlash cart and D64 data is included
=> Minor content fixes (M3U & VSF)

libretro/libretro-mapper.c, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h
Some cleanups and also shot in the dark testing.
=> Touch pointer cleanup

libretro/libretro-core.c, libretro/libretro-core.h, retrodep/snapshot_stream.c, retrodep/video.c, vice/src/raster/raster-line.c
- New zoom mode which is Automatic, except it won't search for the lines and simply disables zoom completely
- Default to the more authentic looking video filter
- Removed snapshot warning noise
=> Auto-Disable Zoom Mode

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-dc.h, libretro/libretro-glue.c, libretro/libretro-glue.h, vice/src/drive/drive.c, vice/src/main.c
- Fixed launching of ZIPs which have files under a directory
- Fixed work disk problems with unit 8 even when using unit 9
- Minor boot log reformat
=> ZIP launch + Work disk fixes

libretro-common/streams/file_stream.c, libretro/libretro-core.c, retrodep/ui.c, retrodep/video.c
- Fixed a few edge cases which threw Automatic Zoom off
- Fixed crash when VFS is enabled and "Read vicerc" core option is disabled
- New video filter option: 0% blur
=> Automatic Zoom improvements, Misc

.gitlab-ci.yml, retrodep/archdep.c, retrodep/monitor/monitor.c
Depends on https://github.com/libretro/RetroArch/pull/13533
=> Add emscripten compilation

retrodep/archdep.c
- VFS is causing issues with PRG files due to `stat` command not giving proper results when content path has non-ascii characters
Closes #453
=> Fix VFS archdep stat

Makefile, libretro/libretro-glue.c
+ Added a hack to NIBTOOLS that made at least one game (Ski or Die) to work.
=> Makefile correction + NIBTOOLS cleanup

vice/src/autostart.c
=> Fix tape FOUND skipper

libretro/libretro-core.c, retrodep/video.c, vice/src/sound.c
- Press Space to continue warping after Autoloadwarp stops warping due to loading music from tape
- New combined frontend fastforward + internal warp instead of laggy loop inside run loop
=> Warp improvements

Makefile, libretro/libretro-core.c
- Removed unnecessary brackets from makefile echo
#498
- Moved printer core option
=> Makefile correction

libretro/libretro-core.c
=> Default empty core option value correction

libretro/libretro-core.c, libretro/libretro-mapper.c
=> D-Pad mouse corrections

libretro/libretro-mapper.c
=> Joypad mouse button corrections

.gitlab-ci.yml, Makefile
https://git.libretro.com/libretro/vice-libretro/-/pipelines/305165
=> apple: use default gitlab runners, fix for newer Xcode versions

libretro/libretro-core.c, vice/src/autostart.c
=> Remove tape load quick progress keypress
