Makefile.libretro, vice/src/arch/libretro/archdep.c
Minimal "make it compile" support for Wii U. BASIC seems to work fine; though it seems when loading a game it either won't detect the drive or the framerate will drop to near-zero (presumably something about the Wii U's less-than-stellar filesystem drivers). I can't really take this any further; someone who actually knows the internals of the emulator would have to look into it. If the Wii build works okay already let me know so I can change the `|| defined(GEKKO)` I added to `|| defined(HW_RVL)` (through a complicated series of events, the unmodified code would result in a null dereference on Wii U).
Thanks again,
-Ash
=> Wii U support (buggy)

libretro/libretro-core.c
VICE requires an additional option to specify the cartridge type for VIC-20 cartridges, which are canonically headerless, with the address bank specified in the file extension (20,40,60,A0,B0). An appropriate cart option must be added for these cartridges (as distributed for example with No-Intro) to load.
=> VIC-20 raw cartridge image support.

libretro/include/config.h
~~~
vice/src/socket.c:147:21: error: static declaration of ‘htonl’ follows non-static declaration
static unsigned int htonl(unsigned int ip)
^~~~~
In file included from ./vice/src/arch/libretro/../unix/socketimpl.h:66:0,
from ./vice/src/arch/libretro/socketimpl.h:43,
from vice/src/socket.c:50:
/usr/include/netinet/in.h:377:17: note: previous declaration of ‘htonl’ was here
extern uint32_t htonl (uint32_t __hostlong)
^~~~~
vice/src/socket.c:176:23: error: static declaration of ‘htons’ follows non-static declaration
static unsigned short htons(unsigned short ip)
^~~~~
In file included from ./vice/src/arch/libretro/../unix/socketimpl.h:66:0,
from ./vice/src/arch/libretro/socketimpl.h:43,
from vice/src/socket.c:50:
/usr/include/netinet/in.h:379:17: note: previous declaration of ‘htons’ was …
=> Fix debug build under Linux

libretro/libretro-core.c, vice/src/arch/libretro/archdep.c
The homedir bug might be why the README specifies _gcc_ as the compiler since I think it only crashes consistently with _clang_ ?
=> Two small bug fixes

vice/src/arch/libretro/archdep.c
fixes build error if VITA is not defined
```
vice/src/arch/libretro/archdep.c:136:6: error: #elif with no expression
#elif
^
```
=> build fix for non-VITA

Makefile.common, libretro-common/compat/compat_strl.c
On Linux:
$ ldd -r vice_x64_libretro.so
undefined symbol: strlcpy_retro__ (./vice_x64_libretro.so)
Adding `compat_strl.c` from libretro-common fixes this.
=> Fix undefined symbol strlcpy_retro__

libretro/libretro-core.c
Moved RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME call into retro_set_environment which triggers the "Start Core" option.
Also fixed a subsequent crash bug caused by retro_load_game( NULL ) call to start up in no-game mode.
=> Allow no-game mode + crash fix.

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
The choice of external C64 palette was only available in Nuklear GUI.
This PR allows setting the palette from Retroarch GUI in Quick Menu -> Options.
=> Allow palette choice in quick menu

vice/src/arch/libretro/defaultkey.inc
Add additional keyboard map for the Vic20 key matrix, existing C64 keymap does not map correctly when building xvic module
=> Add keyboard map for Vic20

libretro/libretro-core.c, libretro/libretro-core.h, libretro/nukleargui/c64menu.i, libretro/nukleargui/gui.i, vice/src/arch/libretro/joy.c, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/vsyncarch.c
Closes #8
Closes #10
Closes #15
Closes #49
The quickmenu->controls options have been providing the
functionality to turn joypad input on/off or switch it to keyboard
for a long time. The retrojoy core option was a leftover when
this functionality didn't exist. Similar the Vice_Controller
core option is now uneccessary.
This commit brings this core on-par with how other cores that
support physical keyboard input work.
To enable a full physical keyboard on desktop machines, when you 
have keyboard bindings to Retropad 0 (cursor keys, A/Z etc.), 
simply change quickmenu->controls port 0 to "Vice Keyboard," 
or "Disconnected". This prevents interplay between the Retropad 
port 0 hotkeys (used for vkbd etc.) and physical keyboard input 
bindings to Retropad 0 that usually exist on desktop …
=> Remove confusing retrojoy option, properly use controls options

libretro/libretro-core.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h
This PR
- fixes the wrong aspect ratio when borders are disabled
- corrects the position and navigation on virtual keyboard when borders are disabled (the window was out of the screen before)
=> Fix aspect ratio and vkbd when borders are off

libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h
When introducing the Border ON/OFF option, the navigation of vkbd with dpad became broken. This fixes that issue.
=> Fix dpad navigation of vkbd when borders are on

libretro/libretro-core.c
Pixel aspect ratio is 15/16, so aspect ratio is 15/10, not 16/10, when borders are off. When borders are on, it comes out as 4/3 so no change there.
Ready to merge, @twinaphex .
=> Use correct aspect ratio when borders off

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
ui.c:
Autostarting a prg by default is put inside a temporary d64 (created in system/vice) and then loaded. This makes loading a LOT longer if true drive emulation is on.
AutostartPrgMode=1 equals inject mode. Any reason to make this an option instead of forcing it?
libretro-core.c:
This change temporarily disables true drive emulation to also prevent drive sound emulation init with prgs. Better ways to do the same?
=> PRG autostart tuning

vice/src/arch/libretro/defaultkey.inc, vice/src/keyboard.c
One restore key is enough & removed useless error messages on keyboard init
=> Less confusing log messages regarding keyboard

libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/nuklear/style.c, libretro/nukleargui/vkboard.i, libretro/vkbd.i, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
"j1" or "j2" can be mentioned anywhere in the path, so all of these work, caps insensitive:
Arkanoid_j1.prg
Arkanoid (j1).prg
j1/Arkanoid.prg
Might this check be too loose? I don't recall cases where the name would already include j1 or j2.
And for those who don't want to rename or reorganize files it can be done with:
retroarch.exe -L core "x64sc -j1 \"path\Arkanoid.prg\""
The command line parsing should also be improved so the emutype is not needed first in the "path".
Also a bonus on pointless drive sound emulation muting with crt files.
Edit: Check is now stricter. Only these will work:
Arkanoid_j1.prg
Arkanoid (j1).prg
Closes #65
=> Joyport force, issue #65

libretro/libretro-core.c, libretro/nukleargui/gui.i, libretro/nukleargui/nuklear/style.c, vice/src/arch/libretro/c64ui.c
More unison in core options, more keyboard theme variations and also turned the drive sound emulation halfway from the SDLVice default range, since 100% is way enough.
=> Core option capitalizations + legacy removals + theme tuning

libretro/libretro-core.c
In practice: Without this the drive resets always when changing any core option. And doing that during loading will lead to having a bad time.
=> Prevent unwanted drive reset during load when updating core options

libretro/libretro-core.c
One palette did not work at all because of a typo.
For some reason Deekay & Ptoing display light gray as dark. I vote for removal.
=> Typo fix and reordering in palettes

libretro/libretro-core.c, libretro/nukleargui/app.c, libretro/nukleargui/gui.i, libretro/nukleargui/retro/nuklear_retro_soft.h, vice/src/arch/libretro/retrostubs.c
Changed the fire button location according to the Retro Standards, which is Retro B is the fire button, not A.
Cleared some default mappings, disabled RetroPad hotkeys for joystick device type, clarified some namings and Retro A toggles virtual keyboard transparency.
=> RetroPad button layout conform + transparency toggle button for vkbd

libretro/libretro-core.c
Prevent some custom settings via command file being overridden by model setting. Previously a standard machine model was being set after custom options in the command line were being parsed. This meant that custom configuration settings were being forced back to standard models. This affected the ability to use the command file to set different Vic20 memory configurations and prevented the use of the command file to run some games and carts which could not be loaded using standard operation.
Now you can load up a Vic20 megacart by creating a text file with a .cmd extension containing the line - 
xvic -cartmega /path/to/rom/mega-cart-name.rom
You can also load Vic20 games which require specific memory configs such as 8k expansion -
xvic -memory 1 /path/to/rom/some-8k-game.d64
=> Improve command file operation

libretro/libretro-core.c
Makes PAL/NTSC switching more enjoyable.
=> Update av_info timing when needed without restart

.gitignore, libretro/libretro-core.c, libretro/retro_disk_control.c, libretro/retro_disk_control.h, libretro/retro_files.c, libretro/retro_files.h, vice/src/arch/libretro/main.c, vice/src/arch/libretro/ui.c, vice/src/initcmdline.c, vice/src/initcmdline.h, vice/src/video/video-resources.c
This reverts commit cd528814507c9fa772c810d8f171776a7f21baa6.
This reverts commit f8be12c0cad25609bb80c9bb35fd355ce3297c16.
- Reading vfl and m3u files specified in 'x64 ...' command line
- Reading vfl and m3u files specified in cmd file
- Executing #COMMAND from m3u file
- Displaying disk image name and possibly disk name on change
instead of default retroarch message
Fixed since previous attempt:
- Crash if command line was empty
- Crash on insert/eject disk (and/or other operations) if image list was empty
- Deleting temporary file before it was closed
=> Allow passing m3u and vfl with other parameters (again)

libretro/libretro-core.c, vice/src/c64/cart/c64cart.c, vice/src/initcmdline.c, vice/src/initcmdline.h
Close #140
Apart from incorrect initialization sequence in `reload_restart` there was a problem in `c64cart.c`, that if you set `CartridgeFile` to some string, then to empty string (e.g. via `resources_set_defaults`) and then back to the same string, it would detach the cartridge, but not attach it again.
=> Fix for cartridge from vicerc ignored

libretro/libretro-core.c, vice/src/c64/cart/c64cart.c, vice/src/initcmdline.c, vice/src/initcmdline.h
- Null-terminate parameters in parse_cmdline
- Mark modified vice code with ifdefs (except snapshot code)
=> Fix m3u command

libretro/libretro-core.c
Basic maintenance:
- Capitalized all core options
- All sublabels end with a "."
- Removed useless statusbar core option
- Hid broken palettes Deekay & Ptoing, because light gray is dark brown (?)
- Reordered core options
Bonus:
- Indentations + tidyings
=> Core option labels according to RetroStandards

libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/ui.c, vice/src/vic20/vic20embedded.c
- Core option for C128 video output (VIC-II / VDC)
-- For now it does the same as pressing the "40/80 display"-key and restarting, because back & forth dual use probably is not practical here..?
-- C128 still needs a completely new virtual keyboard layout, but all in due time
Closes #137 
- Simple fix in VICE source for VIC-20 embedded palettes not working
- VIC & VIC-II audio leak emulation option for true freaks
- Bonus tidyings
=> C128 80 column mode option

libretro/libretro-core.c, vice/src/vsync.c, vice/src/vsync.h
Warp with vsync works by measuring render- and idle-times per frame, then rendering as many frames as fit in the remaining idle time. This ensure screen updates at full display framerate and prompt reaction on warp exit. Without vsync the loop just runs once as t_interframe is 0 because retro_blit() won't block.
The code could also be moved to vsync.c if keeping code in retro_run as small as possible is desired.
=> Add support for warp-mode even if vsync is enabled

vice/src/arch/libretro/uistatusbar.c
Long paths was crashing due to bad practices. Sorry, won't happen again!
Closes #160
=> Fix statusbar path parsing

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
Previously the C64 model would always override the specified SID model,
this is fixed by reordering loading of core options.
New values 'Default FastSID/ReSID' have been added to explicitely enable
SID model selection by C64 model.
=> Enable SID model to override C64 model

libretro/libretro-core.c, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/archdep.h, vice/src/arch/libretro/ui.c, vice/src/sounddrv/soundretro.c
Helps out with #164 but does not solve it.
Also tweaked soundretro a bit, and hopefully the small reduction in sound delay was not placebo, so please test intensively. No ill-effects noticed after a long test session.
And added a small hack to mute the sound at startup and bring it back to max after 3 frames, because 6581 ReSID does that little nasty pop at init.
=> Core option for enabling/disabling 'vicerc'

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
Instead of retrieving SID model set by *_setmodel to call sid_set_engine_model again, just select the engine and leave the SID model as-is.
Also now handle this mechanic properly in ui_init_finalize.
=> Fix SIDmodel 'default' not being applied correctly

README.MD, libretro/libretro-core.c, libretro/libretro-core.h, libretro/nukleargui/gui.i, libretro/nukleargui/nuklear/style.c, libretro/nukleargui/retro/nuklear_retro_soft.h, libretro/nukleargui/vkboard.i, vice/src/arch/libretro/uistatusbar.c
- Enabled zoom mode on X128 & XPLUS4
- Fixed statusbar location on XPET & XCBM2 & PLUS4
- Finetuned VKBD for legibility on transparency modes with text shadow
Plus performance bonuses:
- Removed VKBD buttons rounded borders
- Made Retro_Screen size smaller
Both of those allowed to add 1 more ms of frame delay while VKBD is on. Before those I could only do 12 without getting skipped frames, but now 14 is ok.
=> Zoom mode streamlining

libretro/libretro-core.c, vice/src/arch/libretro/archdep.c
This restores functionality of a few commandline-parameters.
As I found some commandline-options to have no effect at all, I changed this just to see what breaks and works - and was surprised that not only options like -autostart-delay now work, there were no ill side-effects to see, build_params() being declared right above the call suggests it was supposed to be used here.
Maybe some long-gone bug was reason to not pass the options here?
If it turns out there are options that cause an issue when parsed here but work fine when parsed later, they could still be filtered out here.
=> Start core with all parameters, not just core-name

Makefile.x64
A couple of options was mistakenly relying on an unexisting flag, so why not add it also for clarity.
=> Add a COMMONFLAG for x64 just like the others

libretro/libretro-core.c
It turned out that times for the first few rendered frames are not too
stable, causing much too high values.
Capping times to 20msec (=~50fps) should fix that.
=> Fix warp during autostart causing low framerate

libretro/libretro-core.c
x64 is so fast it can actually render the very first frame within less
than a nanosecond - at least RA's get_time_usec() says so.
Division by zero (frametime == 0) crashes so use some more sensible
value in that case.
=> Fix x64 with autostart-warp occasionally crashing on frame 0

libretro/libretro-core.c
Behavior changed to match PUAE for now, even if it is wrong. Which is that a savestate can attach a disc internally, which will confuse RA's index.
Closes #184 again
=> Include only .D64 disks in savestates

README.MD, libretro/libretro-core.c, libretro/libretro-core.h, libretro/nukleargui/gui.i, libretro/nukleargui/nuklear/style.c, libretro/nukleargui/retro/nuklear_retro_soft.h, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/arch/libretro/vsyncarch.c, vice/src/sound.h, vice/src/sounddrv/soundretro.c
- Changed zoom mode centering method from VICE internal `video_canvas_render `to `video_cb`
Closes #172 
- Added filename/path based memory expansion forcing for VIC-20
Closes #186 
- For example `game (8k).prg` or `/8k/game.prg` will force 8KB expansion. `0k` will force none.
- Fixed WIIU cartridge path issue, hopefully
Closes #191
- Finetuned VKBD transparency colors
- Fixed statusbar attached/ejected filename timer from progressing only when statusbar is visible
- Found some sound buffers to test adjust again, and added a placeholder for `audio_batch_cb` if/when it is worth the effort to plug in
- Removed old information from README
=> Bunch of fixes

libretro/libretro-core.c, vice/src/arch/libretro/ui.c
Added missing check for __XSCPU64__
As I found very few checks for that define but many for __X64__ I wonder, does this build currently include everything required to run properly?
=> Fix compiling x64scpu

Makefile.libretro, Makefile.x128, Makefile.x64, Makefile.x64sc, Makefile.x64scpu, Makefile.xcbm2, Makefile.xpet, Makefile.xplus4, Makefile.xvic, libretro/libretro-core.c, vice/src/arch/libretro/ui.c, vice/src/resid/filter8580new.cc, vice/src/sid/resid-33.cc, vice/src/sid/sid-resources.c, vice/src/sid/sid.c, vice/src/sid/sid.h
This is @AnaLogiC76's work taken from https://github.com/libretro/vice-libretro/pull/189, but without resid-fp. Resid-fp has C++11 dependencies which broke buildbot compilation on many platforms.
=> New SID-engine: resid-33 (former PR 189) 

Makefile.libretro
Add flags to ensure source-code complies with C++98 and C99.
Also use g++ and CXXFLAGS for .cc-source as it has now been verified
CXXFLAGS is in sync with CFLAGS, but gcc and g++ will warn if the
specified -std-flag does not match the language in the source-file.
I verified all platforms use gcc/g++, with the exception of ios which uses clang/clang++ which is flag-compatible with gcc, so they all support -std - this makes sure they all use the same language-version regardless if they are old or new.
=> Makefile: Enforce C++98-conformance, use CXXFLAGS

Makefile.libretro, vice/src/residfp/builders/residfp-builder/residfp/FilterModelConfig.cpp, vice/src/residfp/builders/residfp-builder/residfp/FilterModelConfig8580.cpp, vice/src/residfp/builders/residfp-builder/residfp/OpAmp.cpp, vice/src/residfp/builders/residfp-builder/residfp/SID.cpp, vice/src/residfp/builders/residfp-builder/residfp/Spline.cpp, vice/src/residfp/builders/residfp-builder/residfp/WaveformCalculator.cpp, vice/src/residfp/builders/residfp-builder/residfp/resample/SincResampler.cpp, vice/src/residfp/sysincludes.h
Any system-header may only be included from sysincludes.h, this still
was not done in some cpp-files.
=> resid-fp: Fix system-header includes from cpp

Makefile.x64
vicii-clock-stretch.c is not really used on x64, it's only for x128
=> x64: Exclude vicii-clock-stretch.c

libretro/libretro-core.c, libretro/libretro.h, libretro/retro_disk_control.c, libretro/retro_disk_control.h
This PR adds support for libretro disk control interface v1 - in particular, it enables the display of disk 'labels' when using RetroArch's `Current Disk Index` drop-down list (or hotkeys) to select disk images.
By default, disk labels are set to the image filename without extension. When using `m3u` files, the existing `#LABEL:` (or `#EXTINF`) keyword support may be used to specify a custom label - for example, this M3U file:
```
#LABEL:Disk 1 - Side A - Program
ULTIMA5A.D64
#LABEL:Disk 1 - Side B - Dungeon
ULTIMA5B.D64
#LABEL:Disk 2 - Side A - Britannia
ULTIMA5C.D64
#LABEL:Disk 2 - Side B - Underworld
ULTIMA5D.D64
#LABEL:Disk 3 - Side A - Towne
ULTIMA5E.D64
#LABEL:Disk 3 - Side B - Dwelling
ULTIMA5F.D64
#LABEL:Disk 4 - Side A - Castle
ULTIMA5G.D64
#LABEL:Disk 4 - Side B - Keep …
```
=> Add support for disk control interface v1 (disk display labels)

README.MD, libretro/libretro-core.c, vice/src/arch/libretro/ui.c
- Added a simple core option for enabling JiffyDOS (Takes effect after a regular reset)
Closes #215 
- Fixed 'vicerc' core option to enable/disable carts properly
+ Readme finetunings with ROM info
=> JiffyDOS support, Readme cleanups

libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c
Minor fixes:
- Turbofire pulse was off (value 2 was actually 4)
- No reason to allow JiffyDOS core option with anything other than D64 & D81, or is there..?
=> Turbofire & JiffyDOS fix

libretro/libretro-core.c, vice/src/arch/libretro/uistatusbar.c
- To evade JiffyDOS incompatibilities with CRTs, PRGs & TAPs, the allowance method is changed from whitelist to blacklist.
- Also M3U playlists of D64 images will allow, and playlists of TAP images will not
- Fixed not being able to insert disks at all when starting without content
- Drive type defaults to 1541, as in inserting D81s will not work for now, because drive type autodetection happens only on autostart
- Finetuned statusbar
=> Fixes for JiffyDOS, Disk Control & Statusbar

libretro/libretro-core.c, libretro/libretro-keyboard.i, vice/src/arch/libretro/retrostubs.c
- Split "Paddles" joyport type to first two RetroPads:
- Player1 vertical axis = Player2 horizontal axis
- Player1 2nd button = Player2 1st button
- Add speed modifier hotkeys (slower+faster) for paddles/mouse
Because "Paddles" is in fact 2 controllers in one joyport, and currently it is read like a mouse with 2 axis and 2 buttons, this is not convenient for 2 player games, like Panic Analogue, which use paddles as 2 separate entities with one axis and one button.
=> Paddles & mouse improvements

Makefile.common, deps/libz/ioapi.c, deps/libz/ioapi.h, deps/libz/unzip.c, deps/libz/unzip.h, deps/libz/zconf.h, deps/libz/zlib.h, libretro-common/file/file_path.c, libretro-common/include/file/file_path.h, libretro/libretro-core.c, libretro/libretro-core.h, libretro/retro_disk_control.c, libretro/retro_disk_control.h, libretro/retroglue.c, libretro/retroglue.h, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/defaultkey.inc, vice/src/arch/libretro/joy.c, vice/src/arch/libretro/kbd.c, vice/src/arch/libretro/kbd.h, vice/src/arch/libretro/ui.c, vice/src/keyboard.c, vice/src/pet/petembedded.c
Additions:
- M3U+ZIP capabilities on par with PUAE (M3U can include zipped disks, and both can be appended/replaced via Disk Control)
Closes #136 
- Drive type autodetect also when changing disks
- Main reason for this is because the default is 1541, and thus inserting any other disk than D64 when started without content will not work. Also makes it possible to mix different types in the same M3U, even if not really practical.
- Tapes and disks can't be mixed, but Datasette can also be enabled/disabled via Disk Control
Fixes:
- Automatic Aspect Ratio not getting the right region after model change with disabled borders, because the borderless dimension stays the same, and the geometry change was only lurking on those to change
Closes #225 
- Proper PET keyboard layout needed some extra …
=> M3U+ZIP handling, PET fixes

README.MD, libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c
Fixes:
- Browse archive via Load Content was offering the whole path `file.zip#disk.d64` to the emulator instead of extracting and then offering the extracted path
- Drive type autodetection when changing disks changed unnecessarily to the same type, resetting the drive, affecting some games
- Drive type change and TDE change during drive sound output left motor sound running
- Reset was also resetting disk index to the first one, preventing autostarting any other disk
Bonus:
- Added general fallback log function
- Renamed `mouse_x` to `retro_mouse_x` to avoid duplicates
- Removed old information from Readme
=> ZIP + drive fixes, Readme updates

libretro/libretro-core.c, libretro/libretro-core.h, libretro/vkbd.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
Forgot the visibility for the new core option, oops. Also removed all the old border bits.
Bonus addition:
- Manual cropping core options (top/bottom/left/right)
- Overrides zoom if any is not 0, restores zoom if all are 0
=> Remove border stuff, Manual cropping options

README.MD, libretro/libretro-core.c, vice/src/autostart.c
- Disks are created in `saves`, named as `vice_work.<ext>` and labeled as `work-<ext>`
- Having a work disk in device 8 does nothing when starting content
- Skipped less known disk types and devices 10 & 11 for now from polluting the option list
Please point out any inconvenience with this method, and of course if more options are needed.
=> Work disk core option with device selection

libretro/libretro-core.c, vice/src/arch/libretro/uistatusbar.c, vice/src/vsync.c
Automatic model core options for x64 & x64sc:
- Scans for "NTSC|(USA)" and "PAL|(Europe)" tags
- Both PAL/NTSC and C64/C64C can be preferred
- Default is "C64 PAL Automatic"
Work disk improvements:
- No need to reset
- Fixed start content
Sync finetunings:
- GetTicks returns a ticker from get_time_usec instead of fake microSecCounter
- Bypassed internal frameskips and delays
- Warp mode speed improved
- Statusbar updates FPS in 1 second intervals instead of 2 & shows real FPS from both warp and fastforward
=> Automatic model core options, Work disk fixes

libretro/libretro-core.c, libretro/retro_disk_control.c, libretro/retroglue.c, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/archdep.h, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/ui.c, vice/src/printerdrv/output-text.c
Disk Control:
- Allowed CRTs & PRGs in M3Us
- Removed redundant short pathname label fallback in widget, causing duplicate information
Bonus:
- Enabled printer device 4 by default, because why not
- Outputs to `saves/vice_printer.txt`
- `VirtualDevices` was being disabled when TDE was enabled for no apparent reason, which also broke printers
- Improved M3U generation sorting to be more natural, like:
```
1. Spy vs Spy
2. Spy vs Spy II - The Island Caper
3. Spy vs Spy III - Arctic Antics
```
instead of:
```
1. Spy vs Spy II - The Island Caper
2. Spy vs Spy III - Arctic Antics
3. Spy vs Spy
```
=> Disk Control updates, Printer text file output support

libretro/libretro-core.c, libretro/retro_disk_control.c, vice/src/arch/libretro/archdep.h, vice/src/arch/libretro/ui.c, vice/src/drive/drive.c, vice/src/resources.c, vice/src/sound.h, vice/src/sounddrv/soundretro.c, vice/src/video/video-resources.c
Regular:
- Core option for 2nd SID base address
- Reworked warp mode
- Improved autoloadwarp with floppies
VIC-20 updates:
- RAM block set tidying
- Fixed starting carts in M3Us
Core option lipstick:
- Prefixes for hidden options
- Minor reordering
Bonus:
- Sound buffer finetuning
- Achievements environment 
Closes #214 
@AnaLogiC76 You wouldn't happen to have any idea why only reSID-fp creates an endless echo loop if output is in stereo? I forced it to mono for now even with the 2nd SID, because no buffer or fragment fiddling helped. And it isn't that big of a deal really, just curious. I also took a slightly different approach on the warp mode frame thingie, trying to reach maximum reasonable speed, so please take a look at that too if it could be even better/simpler. 
Seems to be fast …
=> 2nd SID, Sound adjustments, VIC-20 updates

libretro/libretro-core.c, vice/src/arch/libretro/uistatusbar.c, vice/src/drive/drive.c
Whoops, for some reason the recent check for `drive->image` added in Autoloadwarper (because disk access with an empty drive resulted in useless and endless warping) caused autowarping to not work with D81s at all..
Changed the detection method to be `retro_get_eject_state`-based and cleaned up some statusbar and `retro_set_eject_state` stuff while I was at it.
Bonus fixed Plus/4 cartridges.
Double bonus: Plus/4 cartridges needed one more special trick to go down smoothly.
=> Autoloadwarp fix for D81s, Statusbar cleanups

vice/src/scpu64/scpu64rom.c, vice/src/scpu64/scpu64rom.h
Evasive maneuvers, because: `error: duplicate symbol: scpu64rom_scpu64_rom`
I'll gladly take any tips that allow getting similar errors with mingw.
=> Fix SuperCPU emscripten

libretro/libretro-core.c
- Playlisted (ZIP/M3U) PRGs got stuck in warp limbo if AutostartWarp is enabled with JiffyDOS (because Jiffy is not allowed with this filetype, and for Jiffy to get disabled post-start, it requires ninja restarting, which confuses the internal autostart so that warp never ends, nhhggh..)
Closes #259 
- Apparently some platforms don't handle `RETRO_ENVIRONMENT_GET_PERF_INTERFACE` `get_time_usec()` properly, thus fallback to the previous method added
Closes #260 
- Prevented PLUS/4 from adding `-cart` for PRGs
Closes #262
=> AutostartWarp fix, Warp tune + cleanup

libretro/libretro-core.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c
- T64 images got stuck in warp mode thanks to Datasette motor controls getting updated on (even if it is not a real tape) but not updated off, which naturally means autoloadwarp thinks loading is still going on
Closes #263 
- SuperCPU kernal core option = no need to hassle with `vicerc`
- Enabled the visibility of mapping core options by default
=> SuperCPU kernal core option, T64 autoloadwarp fix

vice/src/vsync.c
- Removed the skipping of parts which break VDC->VICII transition at C128 bootup on Android and only Android (?!)
- Added a workaround skippage to fix the internal FPS counter which the above mentioned skip removal broke
Closes #258
=> Adjust libretro-hack in internal vsyncing

README.MD, libretro/libretro-core.c, vice/src/arch/libretro/retrostubs.c
- Turbo fire was missing button B and did not override jump button
- Space key is needed so often that why not have it available without forced configuring
- Button X chosen because it does not collide with "RetroPad Face Button Options"
=> Controlling updates

libretro/libretro-core.c, vice/src/arch/libretro/archdep.c, vice/src/tape/tape-snapshot.c
Encountered some problems with savestates and TAP images:
1. Attached tape image is currently included in the state = state load will want to write the image to a temp location = BAD
2. Temp location is determined by environment variable `TMPDIR`, and if not found, defaults to `/tmp`. Neither exists in Windows = BAD
3. If the temp write fails, the state load also fails and the machine resets = BAD
The solution(s):
- Stop including tape images in states and only include images for 1541 (D64) disks, otherwise states are unusable with multidisks (directory listing produces a disk mismatch error), also luckily the temp file will not be written with D64 files (?)
- This will also drop savestate sizes dramatically (tape images can be up to 1,5MB)
- Ignore the images included in old savestates
- …
=> TAP savestate fixes, Restart streamlining

README.md, libretro/libretro-core.c
This is a continuation of PR #271 
Due to the existence of multiple types of the same `.prg` extension, the content needs to be sniffed. The detection function is copied from an existing VICE function with some modifications.
Many cartridge PRGs already work if launched zipped, because they go through a different route (which does cartridge type detection because a M3U playlist will be created, and that will be thrown to Disc Control interface) than startup launching (which does regular autostart type detection).
This will allow launching actual program PRGs (usually found in a floppy disk) and also cartridge PRGs (usually named as `.60`, `.a0` etc.). And as a bonus it also allows simple launching of separated PRG-ROMs which normally need to be assigned to specific memory addresses via …
=> VIC-20 file compatibility improvements

README.md, libretro/libretro-core.c, libretro/libretro-core.h, vice/src/arch/libretro/ui.c
New core options:
- Floppy write protection, applies only to device 8 for now and comes into effect immediately
- Tint for internal palette
Bonus:
- Core option label finetuning and reorganizing
- Changed palette options order to: Gamma, Brightness, Contrast, Saturation, Tint
- Readme updates
- Detach device 9 on unload if it is used for work disk
=> Core options for floppy write protection & internal palette tint

libretro/libretro-core.c
Major:
- Automatic model (PAL+NTSC) core options for VIC-20 like it already is in C64
- Forces per No-Intro filetags and regular `PAL` and `NTSC`
- New model option default is "VIC-20 PAL Automatic"
Minor:
- Forgot to add the VIC-II palette tint option to the show/hide list, oops
- Also noticed that VIC and TED palette options were not added to the list at all, double oops
- Disabled floppy disk drive when launching carts with VIC-20 and PLUS/4
=> Automatic model core option for VIC-20, Video option visibility fixes

libretro/libretro-core.c, libretro/retro_disk_control.c, libretro/retroglue.c, vice/src/arch/libretro/retrostubs.c, vice/src/arch/libretro/uistatusbar.c
VIC-20 additions:
- Paddles etc. analog control port type option
- File path tags to enable full memory expansion (35kB) 
Common:
- Don't update floppy write protection var when it hasn't changed
- Minor reformatting for unzip log output
- Rewordings and adjustments to core option labels
- Internal palette value defaults back to 50%
- Re-enabled CBM620+ models for CBM-II
- Fixed floppy label censoring for rude words (seen when changing disk index)
=> Paddles for VIC-20, Minor fixes

Makefile.xcbm2, Makefile.xcbm5x0, Makefile.xpet, Makefile.xplus4, Makefile.xvic, README.md, libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-mapper.c, libretro/retro_disk_control.c, libretro/retro_disk_control.h, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/drive/drive.c, vice/src/sid/sid.c
- Removed fancy ReSID options (3.3 + FP) from cores that either has very little use for them or need extra SID carts to even have SID
- This trims the core a whopping ~3MB, which is almost half!
- Affects XCBM2, XCBM5x0, XPET, XPLUS4 and XVIC
- Core options tunings (labels and values)
- Disk Control cleanup
- Allow using VKBD with arrow keys even when in Game Focus
- Disabled separate disk index change message in favor of frontend already doing it, but without the actual disk label
=> Misc maintenance

README.md, libretro/libretro-core.c, libretro/retro_disk_control.c, vice/src/arch/libretro/ui.c
- Direct support for VIC-20 Mega-Cart with NvRAM saving to `saves` without `.cmd` hassle
- Allowed the use of relative paths in `.cmd`s
- Fixed 1:1 pixel aspect zoom preset calculations
Closes #284
=> VIC-20 Mega-Cart support

Makefile, libretro/libretro-core.c
This PR adds an OpenDingux (GCW0) target to the makefile.
Tested on an RG350M, the core works perfectly - with the (sizeable) caveat that changing the zoom mode causes a hard crash of RetroArch. It is somewhat difficult to debug this on the RG350 (it requires telnet using a network adaptor, which I do not have...), so until the issue can be resolved the zoom mode option has been disabled on OpenDingux devices.
=> Add OpenDingux target

libretro/libretro-core.c
At present, zoom mode settings are disabled on OpenDingux devices, since they cause the OS to crash. https://github.com/libretro/RetroArch/pull/11436 fixes this issue at the frontend level, so this PR simply re-enables the zoom mode option.
=> OpenDingux: Enable zoom modes

include/PS3_include.h
Build tests for all systems. Now all builds work.
Tested X128 and XVIC, too:
=> All systems - PS3 build fix

libretro/libretro-core.c, vice/src/drive/drive-snapshot.c, vice/src/stamp-h1
Major:
- VICE snapshot behavior hacked to include the attached disk filename instead of disk data
- Allows proper Disc Control index syncing, because disk label included in the data is not reliable enough for matching purposes
- Also saves plenty of space, because the disk data in the state is disk size doubled
- Also hacked to behave the same whether TDE is enabled or not (normally the data is saved only when TDE is enabled)
- Affects only 1541 drive images (D64, G64/NIB) and old states still work, albeit states depending on the included disk data simply need to be saved again after index is changed
Closes #293 
Minor:
- Reset Disc Control index to first entry on Quick Menu -> Restart
Closes #298 
- Fix work disk insertion at startup
- JiffyDOS core option label tweak
- ZIP temp will be …
=> Savestate hacks, Misc fixes

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-mapper.c, vice/src/arch/libretro/archdep.c, vice/src/arch/libretro/ui.c, vice/src/c64/cart/reu.c, vice/src/resources.c
New core options:
- Virtual Device Traps
Closes #297 
- RAM Expansion Unit (C64)
- SFX Sound Expander (C64 & C128)
- EasyFlash Write Protection (C64 & C128)
--- 
Other:
- Per-content vicerc
Closes #296 
- Search `vicerc` first come first serve:
1. `saves/[content].vicerc`
2. `saves/vicerc`
3. `system/vice/vicerc`
- Keyboard pass-through improvements:
- Joystick device type no longer reserves all unused RetroPad button keys for blocking
- RetroPad device type blocks fire/jump/turbofire buttons always and other buttons only when mapped
- Fixed crash when soft resetting without content
- Core option label tweaks
=> New core options, Per-content vicerc

libretro/libretro-core.c, libretro/libretro-graph.c, libretro/libretro-graph.h, libretro/libretro-vkbd.c, vice/src/arch/libretro/uistatusbar.c
This PR optimises the VKBD code as follows:
- Pixel blending is now performed using blargg's packed pixel mixing method (http://blargg.8bitalley.com/info/rgb_mixing.html)
- Array access in several hot loops has been replaced with more efficient pointer manipulation
- Dynamic memory allocation in `Draw_string()`/`Draw_string32()` has been minimised by using global static buffers which are only resized when the required dimensions increase
This reduces the performance overheads of rendering the VKBD by the following amounts (using default settings):
- 16 bit mode: 69%
- 32 bit mode: 74%
The only downside is that the VKBD now has limited/fixed transparency settings: 100%, 75%, 50%, 25%, 0%
I believe that this is sufficient for most users, however, and the performance gain more than makes up …
=> VKBD Optimisations

vice/src/arch/libretro/archdep.c, vice/src/main.c
- Header guards for `GIT_VERSION`
Closes #318 
- Logging for `vicerc`
=> Gitless build fix, vicerc logging

libretro/libretro-core.c, libretro/libretro-core.h
- Automatic models
- New VKBD transparency option visibility
- JiffyDOS autodisable
- Fast x64 defaults ReSID sampling to 'fast'
=> Misc fixes

libretro/libretro-core.c, libretro/libretro-core.h, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/drive/drive.c, vice/src/keyboard.c, vice/src/resources.c
- 2 new options for Autoload warp: "Disk only" & "Tape only"
- Dynamic core option for cartridge selection
- Machine specific system dir `system/vice/C64` etc will be scanned for cart ROMs
=> Autoloadwarp options, Cartridge scanner option

libretro/libretro-core.c, vice/src/arch/libretro/ui.c, vice/src/arch/libretro/uistatusbar.c, vice/src/sound.c
- Substantially faster warping by forcing SID to FastSID during warp
- Random tape load time drops from 50sec to 36sec
- Virtual Device Traps disabled by default, due to causing more harm than good
- Always enabled if TDE is disabled, otherwise disk drives won't work at all
- LED blinking also for tape access
=> Warp Mode speed boost

libretro/libretro-core.c, vice/src/autostart.c, vice/src/drive/drive.c
- Autoloadwarp with disks adjusted to not get stuck with games that for some reason leave the drive LED on always
- Added silent press of `C=` key at `FOUND` prompt when autostarting tapes
- Automatically disable JiffyDOS if True Drive Emulation is disabled
- Internal warping simplified
=> Autoloadwarp + autostart + warp adjustments

README.md, libretro/libretro-core.c, vice/src/autostart.c
- Better handling of TOSEC tags for VIC-20
- Warp Mode tries to take host horsepower into consideration for reducing lag
- Fixed T64 autostart from keeping `C=` pressed indefinitely
=> VIC-20 compatibility, Warp tuning

libretro/libretro-core.c, libretro/libretro-dc.c, libretro/libretro-mapper.c, vice/src/arch/libretro/archdep.c
Major problems found on Linux that do not exist in Windows:
- The way `path_remove_extension()` was used was doing the job twice in Linux, causing empty paths
- `opendir()` on a non-existent directory is a bad idea in Linux, but harmless in Windows
Closes #338 
And some other minor warnings removed.
=> Crash and warning fixes

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-dc.h, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h
A new VKBD hotkey under ShiftLock+Statusbar (STB): Save Disk (SVD)
- First press creates the disk if it does not exist, changes DC index and cycles eject
- Second press changes back to the previous disk
The created disk is automatically appended to DC at next run.
Plus bonus cleanups.
=> Save disk hotkey, VKBD cleanups

libretro/libretro-mapper.c, vice/src/joyport/joystick.c
Fixed fire button issue in "The Detective Game".
Apparently totally bypassing the internal joystick function causes the button to not work randomly. But using the internal function with the default random delay the input is often delayed to the next frame, which is unacceptable as well. Random delay changed to a reasonable calculation, which seems to suit both needs.
=> Joyport fix + cleanup

Makefile
Wno-format was added to common flags recently. In this case it is also necessary to add -Wno-format-security or gcc  ≥ 8 will stop otherwise:
| cc1: error: '-Wformat-security' ignored without '-Wformat' [-Werror=format-security]
| cc1plus: error: '-Wformat-security' ignored without '-Wformat' [-Werror=format-security]
=> Makefile: fix common flags

vice/src/vdrive/vdrive.c
This trivial PR fixes a memory leak identified with ASAN
=> Fix memory leak when initialising virtual drive buffers

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, retrodep/ui.c, vice/src/ram.c, vice/src/vsync.c
- New valid extensions: D2M + D4M (firmwares required)
Closes #374 
- New core option: Datasette Sound (disabled by default)
- Faster randomizing replacement for `RAMInitRandomChance`, because SuperCPU startup is very slow
- Enforce restart on model change in all machines
- Finetuned internal frametime measurements, because statusbar FPS counter took ages to recover from frontend fastforward
=> D2M+D4M extensions, Datasette Sound

README.md, libretro/libretro-core.c, libretro/libretro-mapper.c, retrodep/ui.c, vice/src/datasette/datasette-sound.c, vice/src/resources.c
- Fixed Datasette volume (ARM defaults `char` to unsigned, and one char needs to be signed)
Closes #378 
- Altered `vicerc` parsing to not mind the added ` ### description stuff`
- Added `vicerc` information to README
Closes #380 
- Prevent duplicate VKBD press when keyboard Return is RetroPad Start
=> Datasette volume, 'vicerc' tunings

Makefile.common, include/config.h, libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-graph.c, libretro/libretro-graph.h, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, retrodep/lightpendrv.c, retrodep/lightpendrv.h, retrodep/uistatusbar.c, retrodep/vsyncarch.c, vice/src/drive/drive.c
Major:
- More joyport types: Light pens and guns
- Only mouse + touch control for now
Bonus 3.5 regression fixes:
- Force drive autodetect to 1541-II to prevent unwanted type changes, because change resets the drive, and if a game (Metal Gear) has programmed the drive, disk change will break the game
- Autoloadwarp can't trust LED status that is given to it, because some games (Hostages) will fluctuate PWM enough for the LED to go on and off, causing warp to get stuck, bypassing the very safety measure that is trying to prevent warp from getting stuck (!)
Regular bonus:
- Datasette counter also to VKBD, so that statusbar isn't required for Datasette usage
=> Light pen/gun, Misc fixes

libretro/libretro-core.c
Whoops, all this time the special automatic cart handling for VIC-20 only worked on Windows.. my bad.
Because `snprintf` can use the same variable for input and output on Windows, and I hadn't realized back then yet that it refuses to do that on Linux.
Closes #387
=> XVIC content path fixes

libretro/libretro-core.c, libretro/libretro-core.h, retrodep/snapshot_stream.c, vice/src/ram.c
VIC-20:
- Fixed multipart cart shenanigans that broke Disc Control with regular disks
Closes #392 
- Fixed autoloadwarp caused by disks not being properly inserted in Disc Control
Closes #393 
Other:
- Estimate snapshot size at start for rewind
Closes #394 
Bonus:
- Replace 4 space indents with 3 space in `libretro-core.c`
- Hide Datasette options from X64DTV
- Set memory maps
- Proper error message for snapshot fail
- Hack for a random cartridge launch bug introduced 3.5
- At least one retail cart game (Up 'n Down) gets stuck in black screen when launching via cmdline, even in standalone, requiring a manual reset
=> More XVIC content fixes, Rewind at startup

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-glue.h, libretro/libretro-mapper.c, retrodep/ui.c, vice/src/sound.h
Drive type related fixes:
- Savestate + disc control index sync with D64 multidisks
- JiffyDOS with D64s
Other:
- Removed useless SID limitation and prevented `SidStereo` in `vicerc` from being overwritten with the core option
- Removed unusable core options from SuperCPU
=> Drive type + JiffyDOS fix, Maximum SIDs

libretro/libretro-core.c, libretro/libretro-vkbd.c, retrodep/archdep.c
- Relocated VICE init to `retro_load_game()` from `retro_run()` for making sure core is running before frontend starts to do tasks, such as savestate autoload
- Fixed minor path issues on Linux
- Prevented VKBD Datasette buttons from staying pushed unless Datasette is enabled
=> Core startup cleanup

libretro/libretro-core.c, libretro/libretro-mapper.c, libretro/libretro-mapper.h
Inputs:
- New mapping options for joystick fire 1/2/3
- For those rare games that read them
- New mapping options for other joyport fire and directions
- For simple twinstick use
- New core option for overriding non-joysticks to none/left/right/both analog sticks, defaults to current behavior (left stick). None means both sticks work if the stick remaps are empty, and overrides replace remaps
- For being able to aim with right stick in Portal
Bonus:
- Fixed earlier hack for cart startup restart, which broke savestate autoload with carts only
=> Input additions

libretro/libretro-core.c
`RETRO_ENVIRONMENT_SET_GEOMETRY` is being called with bogus values for `max_width` and `max_height`.
=> Initialize max_width and max_height before the environment call

libretro/libretro-core.c, libretro/libretro-core.h, retrodep/uistatusbar.c, vice/src/drive/drive.c, vice/src/sound.c
- AutoLoadWarp now detects audio, and the old behavior is available via `Ignore audio` options
Closes #422 
- Tape index change presses play automatically
- Core option sublabel adjustments
=> AutoLoadWarp + tape improvements

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-graph.c, libretro/libretro-mapper.c, libretro/libretro-mapper.h, retrodep/ui.c, retrodep/uistatusbar.c, vice/src/drive/drive.c, vice/src/sid/sid.c, vice/src/sound.c
Audio + warp related:
- Streamlined autoloadwarp behavior so that if mode tries to detect audio, it will disable all "noise" generation (disk/tape/leak) automatically
- Improvements to autoloadwarp audio detection when using floppies
- Rewind no longer mutes audio
Other:
- Added joystick directions to core option RetroPad mapper
- Removed possibility to add the same disk to DC list
- Made light gun cursor more visible
=> Autoloadwarp + misc

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-mapper.c, retrodep/video.c, vice/src/sound.c
- A new zoom option for those who use maximum and also don't want to miss out on the sometimes used VIC-II border data. It does not simply toggle zoom off, but calculates the exact lines that ought to be visible, and also centers a few edge cases
Any testing/reporting is welcome!
Also:
+ Removed a warp related hack which caused more problems than it solved
+ Corrected PAR toggle order
=> Automatic Zoom Mode

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-glue.c, libretro/libretro-glue.h, retrodep/snapshot_stream.c, retrodep/ui.c, vice/src/serial/fsdrive.c
Main:
- FileSystem can be used either via launching a directory or via work disk option
- M3U parsing allows quotes for including empty space endings in prg names
- M3U dupecheck fixed to be able to include the same disk with a different label
Other:
- FSDRIVE debug logging removal
- Snapshot error messages to log and as core message
=> Directory FileSystem

libretro/libretro-core.c, libretro/libretro-core.h, retrodep/ui.c
921715e66c86aed76afbe6c9a92b20f1b3790640 added core options for RAM Expansion Units to C64-based cores, but C128 got left out of the party. This brings the x128 emutype in-line with the others.
This is particularly useful right now thanks to [mrsid's brand new Sonic the Hedgehog 1 C64 port](https://www.lemon64.com/forum/viewtopic.php?t=78945), which requires an REU of 256KB or greater (with 512KB, you can load the entire game into the REU on start). While the game of course runs on C64, using the C128 reduces the in-game slowdown.
=> Add REU core option for x128

libretro/libretro-core.c, libretro/libretro-core.h, retrodep/ui.c, vice/src/autostart.c
- Added missing PAL filter oddline options + better default values
Closes #445
- Separated 'OSD' from 'Video' options and added 'System' option category
- Improved work disk in unit 8 to be able to use it when launching non-floppies
=> Oddline filter options, Work disk improvements

libretro/libretro-core.c, retrodep/archdep.c
- Filter gain sublabel + zoom option correction
- Fix crash when internal temp names are used with gzipped files
Closes #449
=> Fix internal gzip extraction

README.md, libretro/libretro-core.c, vice/src/log.c
Band-aid for Plus/4 disk drive issues:
- D64s fail to read
- D81s fail to stop drive sound emulation
Closes #455
=> Fix Plus/4 disk drive issues

libretro/libretro-core.c, retrodep/soundretro.c, vice/src/vsync.c
- Set retro audio as "timing source", which allows the removal of a hack which made fast-forwarding possible
- Audio pacing fix copied from https://github.com/libretro/libretro-uae/pull/499
=> Audio cleanup + pacing

libretro/libretro-core.c, retrodep/ui.c
- Memory banks were applied only at startup model set and not after model override set.
Closes #464
=> Fix VIC-20 memory bank forcing with model forcing

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-dc.c, libretro/libretro-graph.c, libretro/libretro-graph.h, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h, retrodep/keymap.c, retrodep/ui.c, retrodep/uistatusbar.c, retrodep/vsyncarch.c, vice/src/autostart.c, vice/src/tapeport/tapeport.c
VKBD:
- Blended font shadows
- Dimmed surroundings
- Section gap
- Use 4 letters max instead of 3
C128:
- Proper VKBD layout for C128
Closes #468 
- Fix 40/80 toggle switching
Other:
- TCRT extension to valid list
- Auto-enable TDE with TCRT
- Auto-disable TDE with D2M/D4M
=> VKBD enhancements

libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-glue.c, libretro/libretro-vkbd.c, libretro/libretro-vkbd.h, retrodep/uistatusbar.c, vice/src/autostart.c, vice/src/drive/drive.c, vice/src/vsync.c, vice/src/vsync.h
- Backported `autostart.c` from 3.6 to fix autostarting specific PRGs in T64s
- Added option for adjusting the dimming level of VKBD surroundings
- Revised NIBTOOLS hack which made "Ski or Die" work, but broke "Ultimate Wizard"
- Made internal warping smoother without sacrificing maximum speed
=> Autostart backport, Smoother warp

libretro/libretro-core.c, retrodep/uistatusbar.c, vice/src/autostart-prg.c, vice/src/crt.c, vice/src/crt.h, vice/src/drive/drive.c, vice/src/vic20/cart/vic20cart.c
- Recent change of not disabling disk drive by default caused a clash when tape was enabled, ultimately causing statusbar being broken and autoloadwarp to not work
Closes #475 
- Recent autostart backport aimed at fixing tapecart images broke VIC-20 PRG autostart
Closes #476
=> Autostart backport + Autoloadwarp fix

libretro/libretro-core.c, vice/src/autostart.c
ensures the disk is detached before trying to reattach it in the autostart code.
also modifies the `emu_reset` call to allow the `vice_reset` config to be processed when resetting.
=> fix autostart not working on reset

retrodep/archdep.c
Which currently happens internally in VICE when launching gzipped disk images.
Closes #484
=> Ensure TEMP dir exists when it is required via archdep_tmpnam

libretro/libretro-core.c
This PR fixes core variables for frontends that require the variables to be set inside retro_set_environment().
The documentation of `RETRO_ENVIRONMENT_SET_VARIABLES` states:
> This should be called the first time as early as possible (ideally in retro_set_environment).
>
> Afterward it may be called again for the core to communicate updated options to the frontend, but the number of core options must not change from the number in the initial call.
By calling `retro_set_core_options()` both inside retro_set_environment and when loading a game, we satisfy the libretro documentation.
Used to generate Kodi settings for the following cores:
* vice_x128
* vice_x64
* vice_x64dtv
* vice_x64sc
* vice_xcbm2
* vice_xcbm5x0
* vice_xpet
* vice_xplus4
* vice_xscpu64
* vice_xvic
=> Fix core options not set in retro_set_environment()

libretro/libretro-core.c, libretro/libretro-vkbd.c, retrodep/video.c
- Fixed VDC filter core option
- Fixed VDC filter itself which was using the wrong render mode, causing wrong colors
- Enforced VDC "toggle" key (40/80 column mode) to change display output at once
- Fixed Automatic cropping with VDC
- Fixed and streamlined Automatic cropping in general
- Fixed Auto-Disable crop with x64sc (current quick method only worked with fast VIC-II)
Closes #492
=> VDC, VKBD + crop corrections

Makefile, libretro/libretro-core.c, libretro/libretro-core.h, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, retrodep/ui.c, retrodep/video.c
- Added crop functionality for all emutypes
- Added printer core option, defaults to disabled, since it can cause loading issues
- Disabled floppy drives when launching tapes, since it can cause loading issues
- Improved model/region detection+enforcing with automatic models
- Changed default palette to "Internal" for all emutypes
=> Crop + automatic model + misc improvements

Makefile
Per https://github.com/libretro/RetroArch/pull/15688
=> use emar for object file archives, not em++

libretro/libretro-core.c, libretro/libretro-mapper.c, libretro/libretro-vkbd.c, retrodep/arch_keymap.c, retrodep/uistatusbar.c
- Special C128 key mapping corrections + statusbar indicators
Closes #529
- Keep default 1571 when changing disks in C128
Closes #528
- Fix tap restart hang
Closes #530
=> C128 keyboard corrections

libretro/libretro-core.c, libretro/libretro-mapper.c
Added the possibility to use paddles "raw" per hardware joyport instead of forced splitting to RetroPorts.
Closes #540
=> Separate paddles type to 'split' and 'raw'
